install:
  - choco install qt-sdk-windows-x64-mingw_opengl_seh
  - set QTDIR="C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl"
build_script:
  - dir C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\mingw64\bin
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\mingw64\bin
  - qmake QtTest.pro
  - make
