os: unstable
install:
  - choco install InnoSetup
  - set QTDIR="C:\Qt\Qt5.3.2\5.3\mingw482_32"
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - dir C:\Libraries
  - dir C:\Libraries\boost
  - echo %PATH%
  - qmake QtTest.pro
  - mingw32-make
  - dir
  - dir release
  - set QTTEST_RELEASE_PATH=%CD%
  - dir
  - iscc TravisSetup.iss
  - dir
#deploy:
#  provider: Environment
#  name: production
#  on:
#    branch: appveyor
#    appveyor_repo_tag: true
