os: unstable
install:
  #  - choco install InnoSetup
  #- set QTDIR="C:\Qt\Qt5.3.2\5.3\mingw482_32"
  #- set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  #- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - dir %QTDIR%
  - echo %appveyor_build_version%
  #- echo %PATH%
  #  - qmake QtTest.pro
  #- mingw32-make
  #  - dir
  #  - dir release
  #  - set QTTEST_RELEASE_PATH=%CD%
  #  - dir
  #  - dir release
  #  - iscc TravisSetup.iss
  - git rev-parse HEAD >> artifact.txt
  - type artifact.txt
  - dir
artifacts:
  - path: artifact.txt
    name: MyArtifact
deploy:
  #  release: test.txt
  provider: GitHub
  auth_token:
    secure: 9bMCGL2D0e/GK3MGOJu7Ma1hNb6sxAOyEftuonF/tV31LoLLM77+hitI6T3snyCM
  artifact: artifact.txt
  draft: false
  prerelease: false
  on:
    branch: av/deploy
    appveyor_repo_tag: true

