install:
  - choco install qt-sdk-windows-x64-mingw_opengl_seh
  - choco install InnoSetup
  - set QTDIR="C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl"
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\mingw64\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake QtTest.pro
  - mingw32-make
  - set QTTEST_RELEASE_PATH=%CD%
  - iscc TravisSetup.iss
