os: unstable
install:
  - choco install InnoSetup
  - set QTDIR="C:\Qt\Qt5.3.2\5.3\mingw482_32"
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake QtTest.pro
  - mingw32-make
  - dir
  - dir release
  - set QTTEST_RELEASE_PATH=%CD%
  - dir
  - dir release
  - iscc TravisSetup.iss
  - dir
artifacts:
  - path: QtTest_v*.txt
    name: MyArtifact
deploy:
  provider: GitHub
  auth_token:
    secure: 9bMCGL2D0e/GK3MGOJu7Ma1hNb6sxAOyEftuonF/tV31LoLLM77+hitI6T3snyCM
  artifact: /QtTest_v[0-9]+\.[0-9]+\.[0-9]+\.txt/
  draft: false
  prerelease: false
  on:
    branch: av/deploy
    appveyor_repo_tag: true
