os: unstable
install:
#  - choco install InnoSetup curl
  - set QTDIR="C:\Qt\Qt5.3.2\5.3\mingw482_32"
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake QtTest.pro
  - mingw32-make
  - dir
  - dir debug
  - set QTTEST_RELEASE_PATH=%CD%
  - cd debug
  - dir
  - iscc ../TravisSetup.iss
  - dir
  - dir ..
deploy:
  provider: Environment
  name: production
  on:
    branch: appveyor
#    appveyor_repo_tag: true
