branches:
  only:
    - /^av/.*$/
install:
  - choco install InnoSetup
  - set QTDIR="C:\Qt\5.4\mingw491_32"
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - dir %QTDIR%
  #- echo %PATH%
  - qmake QtTest.pro
  - type Makefile.Release
  - mingw32-make
  - dir
  - dir release
  - set QTTEST_RELEASE_PATH=%CD%
  - dir
  - dir release

notifications:
  - provider: Slack
    channel: joker
    auth_token:
      secure: QY4pTvHSFOMIlArGDqQLwE6nE4oPBkWaAGUuFEK2RXWNejGxGy6huwPLN1l0yPCEfrCD9W/3yw9FDxuuFiNLhA==
