environment:
  matrix:
    - conf: pouet
    - conf: choun
#install:
#  - choco install InnoSetup
#  - set QTDIR="C:\Qt\5.4\mingw491_32"
#  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
#  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  #- dir %QTDIR%
  #- echo %PATH%
  #- qmake QtTest.pro
  #- type Makefile.Release
  #- mingw32-make
  #- dir
  #- dir release
  #- set QTTEST_RELEASE_PATH=%CD%
  #- dir
  #- dir release
  - echo conf
