os: unstable
install:
#  - choco install qt-sdk-windows-x86-mingw_opengl
#  - dir c:\Qt
#  - dir C:\Qt\qt-5.3.2-x86-mingw491r1-opengl
  - choco install InnoSetup curl
  - set QTDIR="C:\Qt\Qt5.3.2\5.3\msvc2013_opengl"
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - dir c:\
  - dir c:\MinGW
  - dir c:\Qt\Qt5.3.2

#  - curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.0-mingw.tar.gz
  - qmake QtTest.pro
  - mingw32-make
  - dir
#  - set QTTEST_RELEASE_PATH=%CD%
#  - cd debug
#  - dir
#  - iscc ../TravisSetup.iss
#  - dir
# deploy:
#   provider: Environment
#   name: production
#   on:
#     branch: appveyor
#     appveyor_repo_tag: true
